apiVersion: v1
kind: Pod
metadata:
  name: myk8pod
  labels:
    app:  myapp
spec:
  containers:
  - name: cont1
    image: httpd
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app:  myapp
  ports:
    - port: 80  # clusterip's port
      targetPort: 80 # pod's port
      nodePort: 32000   # nodeport 
